from webbook.models.localisation import Localisation

SQL_MAP_UNKNOWN = {
    998: [{"code": "NONE", "parent": None}],
    999: [{"code": "NONE", "parent": None}],
    9999: [{"code": "NONE", "parent": None}],
}

SQL_MAP_CONTINENT = {
    202: [{"code": "EUR", "parent": None}],
    203: [{"code": "AMR", "parent": None}],
    204: [{"code": "AMR", "parent": None}],
    205: [{"code": "AFR", "parent": None}],
    206: [{"code": "AFR", "parent": None}],
    523: [{"code": "AFR", "parent": None}],
    207: [{"code": "ASA", "parent": None}],
    208: [{"code": "OCE", "parent": None}],
    209: [{"code": "FRA"}, {"code": "EUR", "parent": None}], # France
    210: [{"code": "NONE", "parent": None}],
    211: [{"code": "OCE", "parent": None}]
}

SQL_MAP_COUNTRY = {
    # Europe - EUR
    201: [{"code": "FRA"}, {"code": "EUR", "parent": None}], # France
    401: [{"code": "FRA"}, {"code": "EUR", "parent": None}], # France
    402: [{"code": "DEU"}, {"code": "EUR", "parent": None}],
    403: [{"code": "AUT"}, {"code": "EUR", "parent": None}],
    404: [{"code": "BEL"}, {"code": "EUR", "parent": None}],
    405: [{"code": "CYP"}, {"code": "ASA", "parent": None}],
    406: [{"code": "DNK"}, {"code": "EUR", "parent": None}],
    407: [{"code": "ESP"}, {"code": "EUR", "parent": None}],
    408: [{"code": "FIN"}, {"code": "EUR", "parent": None}],
    410: [{"code": "GRC"}, {"code": "EUR", "parent": None}],
    411: [{"code": "HUN"}, {"code": "EUR", "parent": None}],
    412: [{"code": "IRL"}, {"code": "EUR", "parent": None}],
    413: [{"code": "ISL"}, {"code": "EUR", "parent": None}],
    414: [{"code": "ITA"}, {"code": "EUR", "parent": None}],
    415: [{"code": "LUX"}, {"code": "EUR", "parent": None}],
    416: [{"code": "MKD"}, {"code": "EUR", "parent": None}],
    417: [{"code": "MLT"}, {"code": "EUR", "parent": None}],
    418: [{"code": "MCO"}, {"code": "EUR", "parent": None}],
    419: [{"code": "NOR"}, {"code": "EUR", "parent": None}],
    420: [{"code": "NLD"}, {"code": "EUR", "parent": None}],
    421: [{"code": "POL"}, {"code": "EUR", "parent": None}],
    422: [{"code": "PRT"}, {"code": "EUR", "parent": None}],
    423: [{"code": "ROU"}, {"code": "EUR", "parent": None}],
    424: [{"code": "GBR"}, {"code": "EUR", "parent": None}],
    425: [{"code": "SWE"}, {"code": "EUR", "parent": None}],
    426: [{"code": "CHE"}, {"code": "EUR", "parent": None}],
    427: [{"code": "UKR"}, {"code": "EUR", "parent": None}],

    # Asia - ASA
    463: [{"code": "YEM"}, {"code": "ASA", "parent": None}],
    464: [{"code": "VNM"}, {"code": "ASA", "parent": None}],
    465: [{"code": "TUR"}, {"code": "ASA", "parent": None}],
    466: "", #TO,DO: Not found
    467: [{"code": "THA"}, {"code": "ASA", "parent": None}],
    468: "", #TODO: Not found
    469: "", #TODO: Not found
    470: [{"code": "LKA"}, {"code": "ASA", "parent": None}],
    471: [{"code": "SGP"}, {"code": "ASA", "parent": None}],
    472: [{"code": "PHL"}, {"code": "ASA", "parent": None}],
    473: [{"code": "PSE"}, {"code": "ASA", "parent": None}],
    474: [{"code": "PAK"}, {"code": "ASA", "parent": None}],
    475: [{"code": "NPL"}, {"code": "ASA", "parent": None}],
    476: [{"code": "MMR"}, {"code": "ASA", "parent": None}],
    477: [{"code": "MNG"}, {"code": "ASA", "parent": None}],
    478: [{"code": "MDV"}, {"code": "ASA", "parent": None}],
    479: [{"code": "MYS"}, {"code": "ASA", "parent": None}],
    480: [{"code": "LBN"}, {"code": "ASA", "parent": None}],
    481: [{"code": "LAO"}, {"code": "ASA", "parent": None}],
    482: [{"code": "KWT"}, {"code": "ASA", "parent": None}],
    483: [{"code": "JOR"}, {"code": "ASA", "parent": None}],
    484: [{"code": "JPN"}, {"code": "ASA", "parent": None}],
    485: [{"code": "ISR"}, {"code": "ASA", "parent": None}],
    486: [{"code": "IRN"}, {"code": "ASA", "parent": None}],
    487: [{"code": "IRQ"}, {"code": "ASA", "parent": None}],
    488: [{"code": "IDN"}, {"code": "ASA", "parent": None}],
    489: [{"code": "IND"}, {"code": "ASA", "parent": None}],
    490: "", #TODO: Not found
    491: [{"code": "ARE"}, {"code": "ASA", "parent": None}],
    492: [{"code": "PRK"}, {"code": "ASA", "parent": None}], #INFO: Choose PRK (South Corea]
    493: [{"code": "CHN"}, {"code": "ASA", "parent": None}],
    494: [{"code": "KHM"}, {"code": "ASA", "parent": None}],
    495: [{"code": "BTN"}, {"code": "ASA", "parent": None}],
    496: [{"code": "BGD"}, {"code": "ASA", "parent": None}],
    497: [{"code": "ARM"}, {"code": "ASA", "parent": None}],
    498: [{"code": "SAU"}, {"code": "ASA", "parent": None}],
    499: [{"code": "AFG"}, {"code": "ASA", "parent": None}],

    # America - AMR
    500: [{"code": "USA"}, {"code": "AMR", "parent": None}],
    501: [{"code": "CAN"}, {"code": "AMR", "parent": None}],
    502: [{"code": "MEX"}, {"code": "AMR", "parent": None}],
    503: "", #TODO: Where put this one ?
    504: [{"code": "ARG"}, {"code": "AMR", "parent": None}],
    505: [{"code": "CRI"}, {"code": "AMR", "parent": None}],
    506: [{"code": "BOL"}, {"code": "AMR", "parent": None}],
    507: [{"code": "BLZ"}, {"code": "AMR", "parent": None}],
    508: [{"code": "BRA"}, {"code": "AMR", "parent": None}],
    509: [{"code": "CHL"}, {"code": "AMR", "parent": None}],
    510: [{"code": "COL"}, {"code": "AMR", "parent": None}],
    511: [{"code": "ECU"}, {"code": "AMR", "parent": None}],
    512: [{"code": "GTM"}, {"code": "AMR", "parent": None}],
    513: [{"code": "GUY"}, {"code": "AMR", "parent": None}],
    514: [{"code": "HND"}, {"code": "AMR", "parent": None}],
    515: [{"code": "NIC"}, {"code": "AMR", "parent": None}],
    516: [{"code": "PAN"}, {"code": "AMR", "parent": None}],
    517: [{"code": "PRY"}, {"code": "AMR", "parent": None}],
    518: [{"code": "PER"}, {"code": "AMR", "parent": None}],
    519: "", #TODO: Not found
    520: [{"code": "URY"}, {"code": "AMR", "parent": None}],
    521: [{"code": "VEN"}, {"code": "AMR", "parent": None}],
    522: "", #TODO: Where put this one ?

    # Africa - AFR
    524: [{"code": "DZA"}, {"code": "AFR", "parent": None}],
    525: [{"code": "AGO"}, {"code": "AFR", "parent": None}],
    526: [{"code": "BEN"}, {"code": "AFR", "parent": None}],
    527: [{"code": "BFA"}, {"code": "AFR", "parent": None}],
    528: [{"code": "CMR"}, {"code": "AFR", "parent": None}],
    529: [{"code": "CPV"}, {"code": "AFR", "parent": None}],
    530: [{"code": "CAF"}, {"code": "AFR", "parent": None}],
    531: [{"code": "COM"}, {"code": "AFR", "parent": None}],
    532: [{"code": "COG"}, {"code": "AFR", "parent": None}],
    533: [{"code": "CIV"}, {"code": "AFR", "parent": None}],
    534: [{"code": "DJI"}, {"code": "AFR", "parent": None}],
    535: [{"code": "EGY"}, {"code": "AFR", "parent": None}],
    536: [{"code": "ETH"}, {"code": "AFR", "parent": None}],
    537: [{"code": "GAB"}, {"code": "AFR", "parent": None}],
    538: [{"code": "GMB"}, {"code": "AFR", "parent": None}],
    539: [{"code": "GHA"}, {"code": "AFR", "parent": None}],
    540: [{"code": "GNQ"}, {"code": "AFR", "parent": None}],
    541: [{"code": "KEN"}, {"code": "AFR", "parent": None}],
    542: [{"code": "LBR"}, {"code": "AFR", "parent": None}],
    543: [{"code": "LBY"}, {"code": "AFR", "parent": None}],
    544: [{"code": "MDG"}, {"code": "AFR", "parent": None}],
    545: [{"code": "MLI"}, {"code": "AFR", "parent": None}],
    546: [{"code": "MAR"}, {"code": "AFR", "parent": None}],
    547: [{"code": "MRT"}, {"code": "AFR", "parent": None}],
    548: [{"code": "MOZ"}, {"code": "AFR", "parent": None}],
    549: [{"code": "NAM"}, {"code": "AFR", "parent": None}],
    550: [{"code": "NER"}, {"code": "AFR", "parent": None}],
    551: [{"code": "NGA"}, {"code": "AFR", "parent": None}],
    552: [{"code": "UGA"}, {"code": "AFR", "parent": None}],
    553: [{"code": "RWA"}, {"code": "AFR", "parent": None}],
    554: "", #TODO: Not found
    555: [{"code": "SEN"}, {"code": "AFR", "parent": None}],
    556: "", #TODO: PAS DE PARENT ICI pour SYC
    557: [{"code": "SLE"}, {"code": "AFR", "parent": None}],
    558: [{"code": "SOM"}, {"code": "AFR", "parent": None}],
    559: [{"code": "SDN"}, {"code": "AFR", "parent": None}],
    560: [{"code": "TZA"}, {"code": "AFR", "parent": None}],
    561: [{"code": "TCD"}, {"code": "AFR", "parent": None}],
    562: [{"code": "TGO"}, {"code": "AFR", "parent": None}],
    563: [{"code": "TUN"}, {"code": "AFR", "parent": None}],
    564: [{"code": "ZMB"}, {"code": "AFR", "parent": None}],
    565: [{"code": "ZWE"}, {"code": "AFR", "parent": None}],
    566: "", #TODO: Where put this one?
    567: "", #TODO: Where put this one?

    # Oceanie - OCE
    570: [{"code": "AUS"}, {"code": "OCE", "parent": None}],
    571: [{"code": "NZL"}, {"code": "OCE", "parent": None}],
    572: [{"code": "FJI"}, {"code": "OCE", "parent": None}],
    573: "", #TODO: Where put this one?
    575: "", #TODO: Where put this one?
    576: "", #TODO: 'Ile Maurice' not found to not confuse with 'Maurice' !
    598: "", #TODO: Where put this one?
    599: "", #TODO: Where put this one?

    # Europe - EUR
    600: [{"code": "ALB"}, {"code": "EUR", "parent": None}],
    601: [{"code": "AND"}, {"code": "EUR", "parent": None}],
    603: [{"code": "BLR"}, {"code": "EUR", "parent": None}],
    604: [{"code": "BIH"}, {"code": "EUR", "parent": None}],
    605: [{"code": "BGR"}, {"code": "EUR", "parent": None}],
    606: [{"code": "HRV"}, {"code": "EUR", "parent": None}],
    607: [{"code": "EST"}, {"code": "EUR", "parent": None}],
    608: "", #TODO: Not found
    609: "", #TODO: Not found
    610: "", #TODO: Not found
    611: "", #TODO: Not found
    612: [{"code": "LIE"}, {"code": "EUR", "parent": None}],
    613: [{"code": "LTU"}, {"code": "EUR", "parent": None}],
    614: [{"code": "MDA"}, {"code": "EUR", "parent": None}],
    615: "", #TODO: Not found
    616: [{"code": "RUS"}, {"code": "EUR", "parent": None}],
    617: [{"code": "SMR"}, {"code": "EUR", "parent": None}],
    618: [{"code": "SVK"}, {"code": "EUR", "parent": None}],
    619: [{"code": "SVN"}, {"code": "EUR", "parent": None}],
    620: "", #TODO: Not found

    621: "" #TODO: Not found
}


SQL_MAP_FR_REGION = {
    301: [{"insee": 44}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    302: [{"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    303: [{"insee": 84}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    304: [{"insee": 28}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    305: [{"insee": 27}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    306: [{"insee": 53}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    307: [{"insee": 24}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    308: [{"insee": 44}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    309: [{"insee": 94}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    311: [{"insee": 27}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    312: [{"insee": 28}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    313: [{"insee": 11}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    314: [{"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    315: [{"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    316: [{"insee": 44}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    317: [{"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    318: [{"insee": 32}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    319: [{"insee": 52}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    320: [{"insee": 32}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    321: [{"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    322: [{"insee": 93}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    323: [{"insee": 84}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    325: "" #TODO: Which region to use for DOM-TOM ?
}

SQL_MAP_FR_DEPART = {
    1 : [{"insee": 1}, {"insee": 84}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    2 : [{"insee": 2}, {"insee": 32}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    3 : [{"insee": 3}, {"insee": 84}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    4 : [{"insee": 4}, {"insee": 93}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    5 : [{"insee": 5}, {"insee": 93}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    6 : [{"insee": 6}, {"insee": 93}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    7 : [{"insee": 7}, {"insee": 84}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    8 : [{"insee": 8}, {"insee": 44}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    9 : [{"insee": 9}, {"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    10 : [{"insee": 10}, {"insee": 44}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    11 : [{"insee": 11}, {"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    12 : [{"insee": 12}, {"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    13 : [{"insee": 13}, {"insee": 93}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    14 : [{"insee": 14}, {"insee": 28}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    15 : [{"insee": 15}, {"insee": 84}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    16 : [{"insee": 16}, {"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    17 : [{"insee": 17}, {"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    18 : [{"insee": 18}, {"insee": 24}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    19 : [{"insee": 19}, {"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    20 : [{"insee": 94}, {"code": "FRA"}, { "code": "EUR", "parent": None}], # Corse
    21 : [{"insee": 21}, {"insee": 27}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    22 : [{"insee": 22}, {"insee": 53}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    23 : [{"insee": 23}, {"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    24 : [{"insee": 24}, {"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    25 : [{"insee": 25}, {"insee": 27}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    26 : [{"insee": 26}, {"insee": 84}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    27 : [{"insee": 27}, {"insee": 28}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    28 : [{"insee": 28}, {"insee": 24}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    29 : [{"insee": 29}, {"insee": 53}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    30 : [{"insee": 30}, {"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    31 : [{"insee": 31}, {"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    32 : [{"insee": 32}, {"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    33 : [{"insee": 33}, {"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    34 : [{"insee": 34}, {"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    35 : [{"insee": 35}, {"insee": 53}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    36 : [{"insee": 36}, {"insee": 24}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    37 : [{"insee": 37}, {"insee": 24}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    38 : [{"insee": 38}, {"insee": 84}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    39 : [{"insee": 39}, {"insee": 27}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    40 : [{"insee": 40}, {"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    41 : [{"insee": 41}, {"insee": 24}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    42 : [{"insee": 42}, {"insee": 84}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    43 : [{"insee": 43}, {"insee": 84}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    44 : [{"insee": 44}, {"insee": 52}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    45 : [{"insee": 45}, {"insee": 24}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    46 : [{"insee": 46}, {"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    47 : [{"insee": 47}, {"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    48 : [{"insee": 48}, {"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    49 : [{"insee": 49}, {"insee": 52}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    50 : [{"insee": 50}, {"insee": 28}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    51 : [{"insee": 51}, {"insee": 44}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    52 : [{"insee": 52}, {"insee": 44}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    53 : [{"insee": 53}, {"insee": 52}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    54 : [{"insee": 54}, {"insee": 44}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    55 : [{"insee": 55}, {"insee": 44}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    56 : [{"insee": 56}, {"insee": 53}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    57 : [{"insee": 57}, {"insee": 44}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    58 : [{"insee": 58}, {"insee": 27}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    59 : [{"insee": 59}, {"insee": 32}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    60 : [{"insee": 60}, {"insee": 32}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    61 : [{"insee": 61}, {"insee": 28}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    62 : [{"insee": 62}, {"insee": 32}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    63 : [{"insee": 63}, {"insee": 84}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    64 : [{"insee": 64}, {"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    65 : [{"insee": 65}, {"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    66 : [{"insee": 66}, {"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    67 : [{"insee": 67}, {"insee": 44}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    68 : [{"insee": 68}, {"insee": 44}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    69 : [{"insee": 69}, {"insee": 84}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    70 : [{"insee": 70}, {"insee": 27}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    71 : [{"insee": 71}, {"insee": 27}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    72 : [{"insee": 72}, {"insee": 52}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    73 : [{"insee": 73}, {"insee": 84}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    74 : [{"insee": 74}, {"insee": 84}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    75 : [{"insee": 75}, {"insee": 11}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    76 : [{"insee": 76}, {"insee": 28}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    77 : [{"insee": 77}, {"insee": 11}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    78 : [{"insee": 78}, {"insee": 11}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    79 : [{"insee": 79}, {"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    80 : [{"insee": 80}, {"insee": 32}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    81 : [{"insee": 81}, {"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    82 : [{"insee": 82}, {"insee": 76}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    83 : [{"insee": 83}, {"insee": 93}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    84 : [{"insee": 84}, {"insee": 93}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    85 : [{"insee": 85}, {"insee": 52}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    86 : [{"insee": 86}, {"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    87 : [{"insee": 87}, {"insee": 75}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    88 : [{"insee": 88}, {"insee": 44}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    89 : [{"insee": 89}, {"insee": 27}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    90 : [{"insee": 90}, {"insee": 27}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    91 : [{"insee": 91}, {"insee": 11}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    92 : [{"insee": 92}, {"insee": 11}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    93 : [{"insee": 93}, {"insee": 11}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    94 : [{"insee": 94}, {"insee": 11}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    95 : [{"insee": 95}, {"insee": 11}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    973: [{"insee": 973}, {"insee": 3}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
    974: [{"insee": 974}, {"insee": 4}, {"code": "FRA"}, { "code": "EUR", "parent": None}],
}


SQL_MAP_LIST = [
    SQL_MAP_CONTINENT,
    SQL_MAP_COUNTRY,
    SQL_MAP_FR_REGION,
    SQL_MAP_FR_DEPART,
    SQL_MAP_UNKNOWN,
]
